-- DepEd Authorized Positions Database Insert
-- Organized by: Teaching, School Administration, Related Teaching, and Non-Teaching
-- Last Updated: January 28, 2026

USE deped_evaluation;

-- Clear existing positions (optional - comment out to preserve existing data)
DELETE FROM positions WHERE position_group IN ('A', 'B', 'C', 'TEACHING', 'SCHOOL ADMINISTRATION', 'RELATED TEACHING', 'HIGHER TEACHING', 'NON-TEACHING LEVEL I', 'NON-TEACHING LEVEL II');

-- ========== TEACHING POSITIONS ==========
INSERT INTO positions (position_name, position_group, salary_grade, description) VALUES
('Teacher I', 'TEACHING', '11', 'Teaching Position - Basic Teacher Level');

-- ========== SCHOOL ADMINISTRATION POSITIONS ==========
INSERT INTO positions (position_name, position_group, salary_grade, description) VALUES
('School Principal IV', 'SCHOOL ADMINISTRATION', '22', 'School Administration - Principal Level IV'),
('School Principal III', 'SCHOOL ADMINISTRATION', '21', 'School Administration - Principal Level III'),
('Assistant School Principal III', 'SCHOOL ADMINISTRATION', '20', 'School Administration - Assistant Principal Level III'),
('School Principal II', 'SCHOOL ADMINISTRATION', '20', 'School Administration - Principal Level II'),
('Special School Principal II', 'SCHOOL ADMINISTRATION', '20', 'School Administration - Special Principal Level II'),
('Assistant School Principal II', 'SCHOOL ADMINISTRATION', '19', 'School Administration - Assistant Principal Level II'),
('Head Teacher VI', 'SCHOOL ADMINISTRATION', '19', 'School Administration - Head Teacher Level VI'),
('School Principal I', 'SCHOOL ADMINISTRATION', '19', 'School Administration - Principal Level I'),
('Special School Principal I', 'SCHOOL ADMINISTRATION', '19', 'School Administration - Special Principal Level I'),
('Principal', 'SCHOOL ADMINISTRATION', '19', 'School Administration - Principal'),
('Assistant School Principal I', 'SCHOOL ADMINISTRATION', '18', 'School Administration - Assistant Principal Level I'),
('Assistant Special School Principal', 'SCHOOL ADMINISTRATION', '18', 'School Administration - Assistant Special Principal'),
('Head Teacher V', 'SCHOOL ADMINISTRATION', '18', 'School Administration - Head Teacher Level V'),
('Head Teacher IV', 'SCHOOL ADMINISTRATION', '17', 'School Administration - Head Teacher Level IV'),
('Head Teacher III', 'SCHOOL ADMINISTRATION', '16', 'School Administration - Head Teacher Level III'),
('Head Teacher II', 'SCHOOL ADMINISTRATION', '15', 'School Administration - Head Teacher Level II'),
('Head Teacher I', 'SCHOOL ADMINISTRATION', '14', 'School Administration - Head Teacher Level I');

-- ========== RELATED TEACHING POSITIONS ==========
INSERT INTO positions (position_name, position_group, salary_grade, description) VALUES
('Chief Education Program Specialist', 'RELATED TEACHING', '24', 'Related Teaching - Chief Education Program Specialist'),
('Education Program Supervisor', 'RELATED TEACHING', '22', 'Related Teaching - Education Program Supervisor'),
('Public Schools District Supervisor', 'RELATED TEACHING', '22', 'Related Teaching - Public Schools District Supervisor'),
('Supervising Education Program Specialist', 'RELATED TEACHING', '22', 'Related Teaching - Supervising Education Program Specialist'),
('Senior Education Program Specialist', 'RELATED TEACHING', '19', 'Related Teaching - Senior Education Program Specialist'),
('Senior Science Research Specialist', 'RELATED TEACHING', '19', 'Related Teaching - Senior Science Research Specialist'),
('Vocational Instruction Supervisor III', 'RELATED TEACHING', '18', 'Related Teaching - Vocational Instruction Supervisor III'),
('Vocational Instruction Supervisor II', 'RELATED TEACHING', '17', 'Related Teaching - Vocational Instruction Supervisor II'),
('Education Program Specialist II', 'RELATED TEACHING', '16', 'Related Teaching - Education Program Specialist II'),
('Guidance Coordinator III', 'RELATED TEACHING', '16', 'Related Teaching - Guidance Coordinator III'),
('Science Research Specialist II', 'RELATED TEACHING', '16', 'Related Teaching - Science Research Specialist II'),
('Science Research Technician IV', 'RELATED TEACHING', '16', 'Related Teaching - Science Research Technician IV'),
('Vocational Instruction Supervisor I', 'RELATED TEACHING', '16', 'Related Teaching - Vocational Instruction Supervisor I'),
('Guidance Coordinator II', 'RELATED TEACHING', '15', 'Related Teaching - Guidance Coordinator II'),
('School Farming Coordinator III', 'RELATED TEACHING', '15', 'Related Teaching - School Farming Coordinator III'),
('Teacher Credentials Evaluator II', 'RELATED TEACHING', '15', 'Related Teaching - Teacher Credentials Evaluator II'),
('Guidance Coordinator I', 'RELATED TEACHING', '15', 'Related Teaching - Guidance Coordinator I'),
('School Farming Coordinator II', 'RELATED TEACHING', '14', 'Related Teaching - School Farming Coordinator II'),
('Guidance Counselor III', 'RELATED TEACHING', '13', 'Related Teaching - Guidance Counselor III'),
('School Farming Coordinator I', 'RELATED TEACHING', '13', 'Related Teaching - School Farming Coordinator I'),
('Science Research Technician III', 'RELATED TEACHING', '13', 'Related Teaching - Science Research Technician III'),
('Teacher Credentials Evaluator I', 'RELATED TEACHING', '13', 'Related Teaching - Teacher Credentials Evaluator I'),
('Crafts Education Demonstrator II', 'RELATED TEACHING', '12', 'Related Teaching - Crafts Education Demonstrator II'),
('Education Program Specialist I', 'RELATED TEACHING', '12', 'Related Teaching - Education Program Specialist I'),
('Guidance Counselor II', 'RELATED TEACHING', '12', 'Related Teaching - Guidance Counselor II'),
('Guidance Counselor I', 'RELATED TEACHING', '11', 'Related Teaching - Guidance Counselor I'),
('Science Research Technician II', 'RELATED TEACHING', '11', 'Related Teaching - Science Research Technician II'),
('Teaching-Aids Specialist', 'RELATED TEACHING', '11', 'Related Teaching - Teaching-Aids Specialist'),
('Crafts Education Demonstrator I', 'RELATED TEACHING', '10', 'Related Teaching - Crafts Education Demonstrator I'),
('Education Research Assistant II', 'RELATED TEACHING', '10', 'Related Teaching - Education Research Assistant II'),
('School Farm Demonstrator', 'RELATED TEACHING', '10', 'Related Teaching - School Farm Demonstrator');

-- ========== HIGHER TEACHING POSITIONS ==========
INSERT INTO positions (position_name, position_group, salary_grade, description) VALUES
('Master Teacher IV', 'HIGHER TEACHING', '18', 'Higher Teaching - Master Teacher Level IV'),
('Master Teacher III', 'HIGHER TEACHING', '17', 'Higher Teaching - Master Teacher Level III'),
('Master Teacher II', 'HIGHER TEACHING', '16', 'Higher Teaching - Master Teacher Level II'),
('Master Teacher I', 'HIGHER TEACHING', '15', 'Higher Teaching - Master Teacher Level I');

-- ========== NON-TEACHING POSITIONS (LEVEL I - Senior/Specialist Roles) ==========
INSERT INTO positions (position_name, position_group, salary_grade, description) VALUES
('Attorney V', 'NON-TEACHING LEVEL I', '25', 'Non-Teaching - Attorney Level V'),
('Chief Accountant', 'NON-TEACHING LEVEL I', '24', 'Non-Teaching - Chief Accountant'),
('Chief Administrative Officer', 'NON-TEACHING LEVEL I', '24', 'Non-Teaching - Chief Administrative Officer'),
('Chief Education Supervisor', 'NON-TEACHING LEVEL I', '24', 'Non-Teaching - Chief Education Supervisor'),
('Chief Health Program Officer', 'NON-TEACHING LEVEL I', '24', 'Non-Teaching - Chief Health Program Officer'),
('Engineer V', 'NON-TEACHING LEVEL I', '24', 'Non-Teaching - Engineer Level V'),
('Information Technology Officer III', 'NON-TEACHING LEVEL I', '24', 'Non-Teaching - Information Technology Officer III'),
('Internal Auditor V', 'NON-TEACHING LEVEL I', '24', 'Non-Teaching - Internal Auditor Level V'),
('Planning Officer V', 'NON-TEACHING LEVEL I', '24', 'Non-Teaching - Planning Officer Level V'),
('Project Development Officer V', 'NON-TEACHING LEVEL I', '24', 'Non-Teaching - Project Development Officer Level V'),
('Teacher Camp Superintendent', 'NON-TEACHING LEVEL I', '24', 'Non-Teaching - Teacher Camp Superintendent'),
('Attorney IV', 'NON-TEACHING LEVEL I', '23', 'Non-Teaching - Attorney Level IV'),
('Medical Officer IV', 'NON-TEACHING LEVEL I', '23', 'Non-Teaching - Medical Officer Level IV'),
('Vocational School Administrator II', 'NON-TEACHING LEVEL I', '23', 'Non-Teaching - Vocational School Administrator II'),
('Accountant IV', 'NON-TEACHING LEVEL I', '22', 'Non-Teaching - Accountant Level IV'),
('Assistant Teacher Camp Superintendent', 'NON-TEACHING LEVEL I', '22', 'Non-Teaching - Assistant Teacher Camp Superintendent'),
('Department Legislative Liaison Specialist', 'NON-TEACHING LEVEL I', '22', 'Non-Teaching - Department Legislative Liaison Specialist'),
('Engineer IV', 'NON-TEACHING LEVEL I', '22', 'Non-Teaching - Engineer Level IV'),
('Information Technology Officer II', 'NON-TEACHING LEVEL I', '22', 'Non-Teaching - Information Technology Officer II'),
('Internal Auditor IV', 'NON-TEACHING LEVEL I', '22', 'Non-Teaching - Internal Auditor Level IV'),
('Project Development Officer IV', 'NON-TEACHING LEVEL I', '22', 'Non-Teaching - Project Development Officer Level IV'),
('Project Evaluation Officer IV', 'NON-TEACHING LEVEL I', '22', 'Non-Teaching - Project Evaluation Officer Level IV'),
('Security Officer IV', 'NON-TEACHING LEVEL I', '22', 'Non-Teaching - Security Officer Level IV'),
('Supervising Administrative Officer', 'NON-TEACHING LEVEL I', '22', 'Non-Teaching - Supervising Administrative Officer'),
('Supervising Health Program Officer', 'NON-TEACHING LEVEL I', '22', 'Non-Teaching - Supervising Health Program Officer'),
('Vocational School Administrator I', 'NON-TEACHING LEVEL I', '22', 'Non-Teaching - Vocational School Administrator I'),
('Attorney III', 'NON-TEACHING LEVEL I', '21', 'Non-Teaching - Attorney Level III'),
('Medical Officer III', 'NON-TEACHING LEVEL I', '21', 'Non-Teaching - Medical Officer Level III'),
('Dentist III', 'NON-TEACHING LEVEL I', '20', 'Non-Teaching - Dentist Level III'),
('Accountant III', 'NON-TEACHING LEVEL I', '19', 'Non-Teaching - Accountant Level III'),
('Architect III', 'NON-TEACHING LEVEL I', '19', 'Non-Teaching - Architect Level III'),
('Engineer III', 'NON-TEACHING LEVEL I', '19', 'Non-Teaching - Engineer Level III'),
('Information Systems Analyst III', 'NON-TEACHING LEVEL I', '19', 'Non-Teaching - Information Systems Analyst III'),
('Information Technology Officer I', 'NON-TEACHING LEVEL I', '19', 'Non-Teaching - Information Technology Officer I'),
('Administrative Officer V', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Administrative Officer Level V'),
('Attorney II', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Attorney Level II'),
('Computer Programmer III', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Computer Programmer III'),
('Guidance Services Specialist II', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Guidance Services Specialist II'),
('Health Education And Promotion Officer III', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Health Education And Promotion Officer III'),
('Internal Auditor III', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Internal Auditor Level III'),
('Librarian III', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Librarian Level III'),
('Medical Officer II', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Medical Officer Level II'),
('Nutritionist-Dietitian III', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Nutritionist-Dietitian III'),
('Planning Officer III', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Planning Officer Level III'),
('Project Development Officer III', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Project Development Officer Level III'),
('Senior Administrative Assistant V', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Senior Administrative Assistant Level V'),
('Special Investigator III', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Special Investigator Level III'),
('Statistician III', 'NON-TEACHING LEVEL I', '18', 'Non-Teaching - Statistician Level III'),
('Computer Maintenance Technologist III', 'NON-TEACHING LEVEL I', '17', 'Non-Teaching - Computer Maintenance Technologist III'),
('Dentist II', 'NON-TEACHING LEVEL I', '17', 'Non-Teaching - Dentist Level II'),
('Information Systems Researcher III', 'NON-TEACHING LEVEL I', '17', 'Non-Teaching - Information Systems Researcher III'),
('Accountant II', 'NON-TEACHING LEVEL I', '16', 'Non-Teaching - Accountant Level II'),
('Architect II', 'NON-TEACHING LEVEL I', '16', 'Non-Teaching - Architect Level II'),
('Attorney I', 'NON-TEACHING LEVEL I', '16', 'Non-Teaching - Attorney Level I'),
('Engineer II', 'NON-TEACHING LEVEL I', '16', 'Non-Teaching - Engineer Level II'),
('Guidance Services Specialist I', 'NON-TEACHING LEVEL I', '16', 'Non-Teaching - Guidance Services Specialist I'),
('Information Systems Analyst II', 'NON-TEACHING LEVEL I', '16', 'Non-Teaching - Information Systems Analyst II'),
('Administrative Officer IV', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Administrative Officer Level IV'),
('Agriculturist II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Agriculturist Level II'),
('College Librarian II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - College Librarian Level II'),
('Computer Programming II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Computer Programming II'),
('Creative Arts Specialist II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Creative Arts Specialist II'),
('Human Resource Management Officer II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Human Resource Management Officer II'),
('Internal Auditor II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Internal Auditor Level II'),
('Librarian II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Librarian Level II'),
('Nurse II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Nurse Level II'),
('Nutritionist-Dietitian II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Nutritionist-Dietitian II'),
('Planning Officer II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Planning Officer Level II'),
('Project Development Officer II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Project Development Officer Level II'),
('Publication Production Supervisor', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Publication Production Supervisor'),
('Registrar II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Registrar Level II'),
('Security Officer II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Security Officer Level II'),
('Senior Administrative Assistant III', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Senior Administrative Assistant Level III'),
('Special Investigator II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Special Investigator Level II'),
('Statistician II', 'NON-TEACHING LEVEL I', '15', 'Non-Teaching - Statistician Level II'),
('Administrative Officer III', 'NON-TEACHING LEVEL I', '14', 'Non-Teaching - Administrative Officer Level III'),
('Cashier II', 'NON-TEACHING LEVEL I', '14', 'Non-Teaching - Cashier Level II'),
('Dentist I', 'NON-TEACHING LEVEL I', '14', 'Non-Teaching - Dentist Level I'),
('Health Education and Promotion Officer II', 'NON-TEACHING LEVEL I', '14', 'Non-Teaching - Health Education and Promotion Officer II'),
('Records Officer II', 'NON-TEACHING LEVEL I', '14', 'Non-Teaching - Records Officer Level II'),
('Senior Administrative Assistant II', 'NON-TEACHING LEVEL I', '14', 'Non-Teaching - Senior Administrative Assistant Level II'),
('Supply Officer II', 'NON-TEACHING LEVEL I', '14', 'Non-Teaching - Supply Officer Level II');

-- ========== NON-TEACHING POSITIONS (LEVEL II - Support Staff Roles) ==========
INSERT INTO positions (position_name, position_group, salary_grade, description) VALUES
('College Librarian I', 'NON-TEACHING LEVEL II', '13', 'Non-Teaching - College Librarian Level I'),
('School Librarian III', 'NON-TEACHING LEVEL II', '13', 'Non-Teaching - School Librarian Level III'),
('Senior Administrative Assistant I', 'NON-TEACHING LEVEL II', '13', 'Non-Teaching - Senior Administrative Assistant Level I'),
('Vocational Placement Coordinator I', 'NON-TEACHING LEVEL II', '13', 'Non-Teaching - Vocational Placement Coordinator I'),
('Accountant I', 'NON-TEACHING LEVEL II', '12', 'Non-Teaching - Accountant Level I'),
('Administrative Assistant VI', 'NON-TEACHING LEVEL II', '12', 'Non-Teaching - Administrative Assistant Level VI'),
('Legal Assistant II', 'NON-TEACHING LEVEL II', '12', 'Non-Teaching - Legal Assistant Level II'),
('School Librarian II', 'NON-TEACHING LEVEL II', '12', 'Non-Teaching - School Librarian Level II'),
('Accounting Clerk I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Accounting Clerk Level I'),
('Administrative Assistant V', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Administrative Assistant Level V'),
('Administrative Officer I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Administrative Officer Level I'),
('Administrative Officer II', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Administrative Officer Level II'),
('Agriculturist I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Agriculturist Level I'),
('Aquaculturist I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Aquaculturist Level I'),
('Budget Officer I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Budget Officer Level I'),
('Communication Equipment Operator IV', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Communication Equipment Operator Level IV'),
('Computer Maintenance Technologist I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Computer Maintenance Technologist Level I'),
('Creative Arts Specialist I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Creative Arts Specialist Level I'),
('Dormitory Manager II', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Dormitory Manager Level II'),
('Fiscal Examiner I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Fiscal Examiner Level I'),
('Human Resource Management Officer I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Human Resource Management Officer I'),
('Internal Auditor I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Internal Auditor Level I'),
('Librarian I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Librarian Level I'),
('Nurse I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Nurse Level I'),
('Nutritionist-Dietitian I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Nutritionist-Dietitian I'),
('Planning Officer I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Planning Officer Level I'),
('Project Development Officer I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Project Development Officer Level I'),
('Psychologist I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Psychologist Level I'),
('Registrar I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Registrar Level I'),
('Social Welfare Officer I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Social Welfare Officer Level I'),
('Statistician I', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Statistician Level I'),
('Warehouseman III', 'NON-TEACHING LEVEL II', '11', 'Non-Teaching - Warehouseman Level III'),
('Cashier I', 'NON-TEACHING LEVEL II', '10', 'Non-Teaching - Cashier Level I'),
('Cinematographer I', 'NON-TEACHING LEVEL II', '10', 'Non-Teaching - Cinematographer Level I'),
('Computer File Librarian II', 'NON-TEACHING LEVEL II', '10', 'Non-Teaching - Computer File Librarian Level II'),
('Legal Assistant I', 'NON-TEACHING LEVEL II', '10', 'Non-Teaching - Legal Assistant Level I'),
('Supply Officer I', 'NON-TEACHING LEVEL II', '10', 'Non-Teaching - Supply Officer Level I'),
('Administrative Assistant III', 'NON-TEACHING LEVEL II', '9', 'Non-Teaching - Administrative Assistant Level III'),
('Communication Equipment Operator III', 'NON-TEACHING LEVEL II', '9', 'Non-Teaching - Communication Equipment Operator Level III'),
('Dormitory Manager I', 'NON-TEACHING LEVEL II', '9', 'Non-Teaching - Dormitory Manager Level I'),
('Printing Foreman', 'NON-TEACHING LEVEL II', '9', 'Non-Teaching - Printing Foreman'),
('Science Research Assistant', 'NON-TEACHING LEVEL II', '9', 'Non-Teaching - Science Research Assistant'),
('Science Research Technician I', 'NON-TEACHING LEVEL II', '9', 'Non-Teaching - Science Research Technician Level I'),
('Senior Bookkeeper', 'NON-TEACHING LEVEL II', '9', 'Non-Teaching - Senior Bookkeeper'),
('Administrative Assistant II', 'NON-TEACHING LEVEL II', '8', 'Non-Teaching - Administrative Assistant Level II'),
('Aquacultural Technician II', 'NON-TEACHING LEVEL II', '8', 'Non-Teaching - Aquacultural Technician Level II'),
('Artist-Illustrator II', 'NON-TEACHING LEVEL II', '8', 'Non-Teaching - Artist-Illustrator Level II'),
('Bookkeeper', 'NON-TEACHING LEVEL II', '8', 'Non-Teaching - Bookkeeper'),
('Computer File Librarian I', 'NON-TEACHING LEVEL II', '8', 'Non-Teaching - Computer File Librarian Level I'),
('Disbursing Officer II', 'NON-TEACHING LEVEL II', '8', 'Non-Teaching - Disbursing Officer Level II'),
('Draftsman II', 'NON-TEACHING LEVEL II', '8', 'Non-Teaching - Draftsman Level II'),
('Internal Auditing Assistant', 'NON-TEACHING LEVEL II', '8', 'Non-Teaching - Internal Auditing Assistant'),
('Project Development Assistant', 'NON-TEACHING LEVEL II', '8', 'Non-Teaching - Project Development Assistant'),
('Security Guard III', 'NON-TEACHING LEVEL II', '8', 'Non-Teaching - Security Guard Level III'),
('Administrative Assistant I', 'NON-TEACHING LEVEL II', '7', 'Non-Teaching - Administrative Assistant Level I'),
('Copy Reader', 'NON-TEACHING LEVEL II', '7', 'Non-Teaching - Copy Reader'),
('Accounting Clerk II', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Accounting Clerk Level II'),
('Administrative Aide VI', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Administrative Aide Level VI'),
('Clerk III', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Clerk Level III'),
('Communication Equipment Operator II', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Communication Equipment Operator Level II'),
('Disbursing Officer I', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Disbursing Officer Level I'),
('Draftsman I', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Draftsman Level I'),
('Electronics And Communication Equipment Technician I', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Electronics And Communication Equipment Technician I'),
('Laboratory Technician I', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Laboratory Technician Level I'),
('Mechanic II', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Mechanic Level II'),
('Mechanical Plant Operator II', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Mechanical Plant Operator Level II'),
('Photoengraver II', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Photoengraver Level II'),
('Proofreader II', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Proofreader Level II'),
('Typesetter II', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Typesetter Level II'),
('Utility Foreman', 'NON-TEACHING LEVEL II', '6', 'Non-Teaching - Utility Foreman'),
('Administrative Aide V', 'NON-TEACHING LEVEL II', '5', 'Non-Teaching - Administrative Aide Level V'),
('Handicraft Worker II', 'NON-TEACHING LEVEL II', '5', 'Non-Teaching - Handicraft Worker Level II'),
('Legal Aide', 'NON-TEACHING LEVEL II', '5', 'Non-Teaching - Legal Aide'),
('Master Fisherman I', 'NON-TEACHING LEVEL II', '5', 'Non-Teaching - Master Fisherman Level I'),
('Security Guard II', 'NON-TEACHING LEVEL II', '5', 'Non-Teaching - Security Guard Level II'),
('Administrative Aide IV', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Administrative Aide Level IV'),
('Clerk II', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Clerk Level II'),
('Communication Equipment Operator I', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Communication Equipment Operator Level I'),
('Dental Aide', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Dental Aide'),
('Fiscal Clerk I', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Fiscal Clerk Level I'),
('Heavy Equipment Operator I', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Heavy Equipment Operator Level I'),
('Houseparent I', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Houseparent Level I'),
('Marine Engineman I', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Marine Engineman Level I'),
('Mechanic I', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Mechanic Level I'),
('Mechanical Plant Operator I', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Mechanical Plant Operator Level I'),
('Metal Worker I', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Metal Worker Level I'),
('Nursing Attendant I', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Nursing Attendant Level I'),
('Statistician Aide', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Statistician Aide'),
('Telegram Carrier', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Telegram Carrier'),
('Watchman II', 'NON-TEACHING LEVEL II', '4', 'Non-Teaching - Watchman Level II'),
('Administrative Aide III', 'NON-TEACHING LEVEL II', '3', 'Non-Teaching - Administrative Aide Level III'),
('Clerk I', 'NON-TEACHING LEVEL II', '3', 'Non-Teaching - Clerk Level I'),
('Cook I', 'NON-TEACHING LEVEL II', '3', 'Non-Teaching - Cook Level I'),
('Coxswain', 'NON-TEACHING LEVEL II', '3', 'Non-Teaching - Coxswain'),
('Driver I', 'NON-TEACHING LEVEL II', '3', 'Non-Teaching - Driver Level I'),
('Fisherman', 'NON-TEACHING LEVEL II', '3', 'Non-Teaching - Fisherman'),
('Handicraft Worker I', 'NON-TEACHING LEVEL II', '3', 'Non-Teaching - Handicraft Worker Level I'),
('Lineman I', 'NON-TEACHING LEVEL II', '3', 'Non-Teaching - Lineman Level I'),
('Security Guard I', 'NON-TEACHING LEVEL II', '3', 'Non-Teaching - Security Guard Level I'),
('Administrative Aide II', 'NON-TEACHING LEVEL II', '2', 'Non-Teaching - Administrative Aide Level II'),
('Construction And Maintenance Man', 'NON-TEACHING LEVEL II', '2', 'Non-Teaching - Construction And Maintenance Man'),
('Farm Worker I', 'NON-TEACHING LEVEL II', '2', 'Non-Teaching - Farm Worker Level I'),
('Guesthouse Caretaker', 'NON-TEACHING LEVEL II', '2', 'Non-Teaching - Guesthouse Caretaker'),
('Light Equipment Operator', 'NON-TEACHING LEVEL II', '2', 'Non-Teaching - Light Equipment Operator'),
('Nurse Maid I', 'NON-TEACHING LEVEL II', '2', 'Non-Teaching - Nurse Maid Level I'),
('Reproduction Machine Operator I', 'NON-TEACHING LEVEL II', '2', 'Non-Teaching - Reproduction Machine Operator I'),
('Watchman I', 'NON-TEACHING LEVEL II', '2', 'Non-Teaching - Watchman Level I'),
('Administrative Aide I', 'NON-TEACHING LEVEL II', '1', 'Non-Teaching - Administrative Aide Level I'),
('Utility Worker I', 'NON-TEACHING LEVEL II', '1', 'Non-Teaching - Utility Worker Level I');
